name: Build
on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'
      - run: corepack enable
      - run: corepack install
      - run: yarn install --immutable
      - run: yarn tsc
      - run: yarn build:backend
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=sha
      - name: Build image 
        uses: docker/build-push-action@v6
        with:
          context: .
          file: packages/backend/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}